buildscript {
    repositories {
        mavenCentral()
		maven {
		  url "https://plugins.gradle.org/m2/"
		}
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:4.1.0")
        classpath "com.github.jk1:gradle-license-report:2.0"
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'war'
apply plugin: 'jacoco'
apply plugin: "project-report"
apply plugin: "com.github.jk1.dependency-license-report"

bootJar {
    enabled = false
}

bootWar {
    archiveBaseName = 'SpringWebApps'
    archiveVersion = '0.1.0'
}

repositories {
    mavenCentral()
}

sourceCompatibility = 17
targetCompatibility = 17

dependencies {
    implementation group: 'com.lmax', name: 'disruptor', version:'4.0.0'
    compileOnly("org.springframework.boot:spring-boot-devtools")
	  implementation("org.springframework.boot:spring-boot-starter-web:4.1.0")
	  implementation 'org.springframework.boot:spring-boot-starter-log4j2:4.1.0'
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:4.1.0")
    implementation("org.springframework.boot:spring-boot-starter-data-rest:4.1.0")
    implementation("com.h2database:h2:2.4.240")
    implementation group: 'org.modelmapper', name: 'modelmapper', version: '3.2.6'
    implementation group: 'com.microsoft.sqlserver', name: 'mssql-jdbc', version: '9.4.0.jre8'
    implementation group: 'jakarta.xml.bind', name: 'jakarta.xml.bind-api', version: '4.0.5'
    implementation group: 'com.sun.xml.bind', name: 'jaxb-core', version: '4.0.9'
    implementation group: 'com.sun.xml.bind', name: 'jaxb-impl', version: '4.0.9'
    implementation group: 'jakarta.activation', name: 'jakarta.activation-api', version: '2.1.2'
    implementation group: 'org.apache.tomcat', name: 'tomcat-dbcp', version: '10.1.7'
    implementation("org.springframework.boot:spring-boot-starter-websocket:4.1.0")
    implementation("org.webjars:webjars-locator-core")
    implementation("org.webjars:sockjs-client:1.5.1")
    implementation("org.webjars:stomp-websocket:2.3.4")
    implementation("org.webjars:bootstrap:5.3.8")
    implementation("org.webjars:jquery:4.0.0")
    testImplementation('org.springframework.boot:spring-boot-starter-test:4.1.0') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
	implementation("jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.0")
	runtimeOnly("org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1")
	implementation("org.apache.tomcat.embed:tomcat-embed-jasper")
    providedRuntime("org.springframework.boot:spring-boot-starter-tomcat:4.1.0")
}

test {
	useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}
configurations {
	all {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
	}
}

task stage {
    dependsOn bootWar
}
