
spring.jpa.show-sql = true
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.http.converters.preferred-json-mapper=jackson2
spring.websocket.messaging.preferred-json-mapper=jackson2
